#!/usr/bin/env node
// regenerates checked-in derived content; test/generated.test.js fails when it's stale:
// - the README's command reference, from src/spec.js
// - the code stamp in src/extension/background.js
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { ROOT, BRIDGE_FILE, STAMP, bridgeHash } from '../src/common.js'
import { renderCommands } from '../src/spec.js'

export const README_FILE = path.join(ROOT, 'README.md')
const START = '<!-- commands:start (generated by scripts/gen.js from src/spec.js) -->'
const END = '<!-- commands:end -->'

/** @param {string} readme */
export function withCommands(readme) {
  const a = readme.indexOf(START), b = readme.indexOf(END)
  if (a === -1 || b === -1) throw new Error('README is missing the commands markers')
  return readme.slice(0, a + START.length) + '\n```\n' + renderCommands() + '\n```\n' + readme.slice(b)
}

/** @param {string} src */
export const stamped = (src) => src.replace(STAMP, `const CODE = '${bridgeHash(src)}'`)

if (fileURLToPath(import.meta.url) === path.resolve(process.argv[1] || '')) {
  fs.writeFileSync(README_FILE, withCommands(fs.readFileSync(README_FILE, 'utf8')))
  fs.writeFileSync(BRIDGE_FILE, stamped(fs.readFileSync(BRIDGE_FILE, 'utf8')))
  console.log('updated README.md command reference and background.js code stamp')
}
